# name: Node.js CI

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [18]

#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v2
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: "npm"
#       - run: npm install
#       - run: npm run lint
#       - run: npm run build
#       - run: npm test
name: Update Fork

on:
  push:
    branches: [test_fork]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "${{ github.server_url }}/${{ github.repository }}"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.ATHENA_KEY }}
      - run: git branch -a
      - run: git remote -v
      - run: git remote add upstream ${{ secrets.ATHENA_UPSTREAM_URL }}
      - run: git remote -v

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - run: git push upstream ${{ steps.extract_branch.outputs.branch }}:${{ steps.extract_branch.outputs.branch }}