name: Update Fork

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - env:
            super_secret: ${{ secrets.ATHENA_UPSTREAM_URL }}
        if: ${{ env.super_secret == '' }}
        run: exit 1

      - run: echo "${{ github.server_url }}/${{ github.repository }}"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.ATHENA_KEY }}
      - run: git remote add upstream ${{ secrets.ATHENA_UPSTREAM_URL }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - run: git push upstream ${{ steps.extract_branch.outputs.branch }}:${{ steps.extract_branch.outputs.branch }}